(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(Man-notify-method 'aggressive t)
 '(bookmark-save-flag 1)
 '(byte-compile-warnings '(not cl-functions))
 '(compilation-scroll-output t)
 '(completion-category-overrides '((file (styles partial-completion))))
 '(completion-cycle-threshold 3)
 '(completion-styles '(orderless basic))
 '(completions-detailed t)
 '(confirm-kill-emacs 'y-or-n-p)
 '(corfu-auto t)
 '(corfu-auto-prefix 2)
 '(corfu-cycle t)
 '(crafted-startup-inhibit-splash t)
 '(crafted-startup-module-list '(crafted-startup-recentf crafted-startup-projects))
 '(dired-auto-revert-buffer t)
 '(dired-dwim-target t)
 '(dired-kill-when-opening-new-dired-buffer t)
 '(ediff-window-setup-function 'ediff-setup-windows-plain t)
 '(eglot-autoshutdown t t)
 '(eshell-scroll-to-bottom-on-input 'this t)
 '(fancy-splash-image
   "/data/data/org.gnu.emacs/files/.emacs.d/crafted-emacs/system-crafters-logo.png")
 '(fast-but-imprecise-scrolling t)
 '(global-auto-revert-non-file-buffers t)
 '(ibuffer-movement-cycle nil)
 '(ibuffer-old-time 24)
 '(inhibit-splash-screen t)
 '(inhibit-startup-message t)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(judy-transparency-enable-on-startup t)
 '(judy-transparency-startup-value 94)
 '(kill-do-not-save-duplicates t)
 '(large-file-warning-threshold nil)
 '(load-prefer-newer t)
 '(marginalia-annotators
   '(marginalia-annotators-heavy marginalia-annotators-light nil) t)
 '(modus-themes-bold-constructs t)
 '(modus-themes-headings
   '((1 rainbow overline 1.0) (2 rainbow 1.0) (3 rainbow bold 1.0)
     (t semilight 1.0)))
 '(modus-themes-italic-constructs t)
 '(modus-themes-lang-checkers '(straight-underline background) t)
 '(modus-themes-org-blocks 'gray-background)
 '(modus-themes-paren-match '(bold) t)
 '(modus-themes-syntax '(yellow-comments) t)
 '(org-hide-emphasis-markers t)
 '(org-link-descriptive t)
 '(org-mouse-1-follows-link t)
 '(org-return-follows-link t)
 '(package-archive-priorities
   '(("gnu" . 99) ("nongnu" . 80) ("stable" . 70) ("melpa" . 0)))
 '(package-pinned-packages '((cider . "gnu") (clojure-mode . "gnu")))
 '(package-selected-packages nil)
 '(package-vc-selected-packages
   '((compat :vc-backend Git :url "https://github.com/junghan0611/compat")
     (outli :vc-backend Git :url "https://github.com/jdtsmith/outli")
     (term-keys :vc-backend Git :url "https://github.com/junghan0611/term-keys")))
 '(scheme-program-name "guile" t)
 '(scroll-conservatively 101)
 '(scroll-margin 0)
 '(scroll-preserve-screen-position t)
 '(speedbar-frame-parameters
   '((name . "speedbar") (title . "speedbar") (minibuffer) (border-width . 2)
     (menu-bar-lines . 0) (tool-bar-lines . 0) (unsplittable . t)
     (left-fringe . 10)))
 '(speedbar-update-flag t)
 '(speedbar-use-images nil)
 '(switch-to-buffer-in-dedicated-window 'pop)
 '(switch-to-buffer-obey-display-actions t)
 '(tab-always-indent 'complete)
 '(use-dialog-box nil)
 '(use-short-answers t)
 '(vc-follow-symlinks t)
 '(vertico-cycle t)
 '(xref-show-definitions-function 'xref-show-definitions-completing-read))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#181a26" :foreground "gray80" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 119 :width normal :family "SEC Regular_SamsungKoreanR" :foundry "GOOG")))))
